print ("what is your name human?")
name = input()
print (name)
print()
print("how old are you?")
age = int(input ())
print (age)
print ()
print ("how tall are you?")
height = float(input())
print (height)
print()
print ("how much do u weigh?")
weight = int(input())
print (weight)
print ()
bmi = ((weight)/((height)**2))
print (bmi)
