print ("what is your name human?")
name = input()
print (name)
print()
print("how old are you? (in years)")
age = int(input())
print (age)
print ()
print ("how tall are you? (in meters)")
height = float(input())
print (height)
print()
print ("how much do u weigh? (in KGS)")
weight = int(input())
print (weight)
print ()
bmi = ((weight)/((height)**2))
print (f"{name} you are {age} years old and your BMI is {bmi:.2f}")

